#include "include/testsuite.h"

int main()
{
	test_main_aes();
	test_main_arcfour();
	test_main_arctwo();	
	test_main_base16();
	test_main_base64();
	test_main_blowfish();
	test_main_buffer();
	test_main_camellia();	
	test_main_cast128();
	test_main_cbc();
	test_main_ccm();
	test_main_cfb();
	test_main_chacha_poly1305();
	test_main_chacha();
	test_main_cmac();
	test_main_ctr();
	test_main_des();
	test_main_des3();
	test_main_eax();
	test_main_gcm();
	test_main_gosthash94();
	test_main_hkdf();
	test_main_hmac();
	test_main_knuth();
	test_main_md2();
	test_main_md4();
	test_main_md5_compat();
	test_main_md5();
	test_main_meta_aead();
	test_main_meta_armor();
	test_main_meta_ciphers();
	test_main_meta_hash();
	test_main_meta_mac();
	test_main_pbkdf2();
	test_main_poly1305();
	test_main_ripemd160();
	test_main_salsa20();
	test_main_serpent();
	test_main_sha1();
	test_main_sha1_huge();
	test_main_sha3_224();
	test_main_sha3_256();
	test_main_sha3_384();
	test_main_sha3_512();
	test_main_sha3_permute();
	test_main_sha224();
	test_main_sha256();
	test_main_sha384();
	test_main_sha512();
	test_main_sha512_224();
	test_main_sha512_256();
	test_main_shake256();
	test_main_twofish();
	test_main_umac();
	test_main_xts();
	test_main_yarrow();

	return 0;
}
